### ISSUE TITLE
NoMethodError: undefined method `[]' for XDG:Module

### ISSUE THREAD

**Issue by saigkill** [bkuhlmann/xdg#2]
## Overview

By using the XDG module i'm getting a undefined method.
## Screenshots/Screencasts

<img width="535" alt="2020-06-28 20_36_56-Merge remote-tracking branch 'origin_master' · saigkill_publican_creators@0c53fb" src="https://user-images.githubusercontent.com/75621/85955504-4d794600-b97f-11ea-983e-1a91f482e5cf.png">

## Steps to Recreate

require 'fileutils'
require 'xdg'
desc 'Install config'
task :install_config do
  sys_xdg = XDG['CONFIG_HOME']
  from = 'etc/publicancreators.cfg'
  sysconf_dir = "#{sys_xdg}/publican_creators"
  FileUtils.mkdir(sysconf_dir) unless File.exist?(sysconf_dir)
  FileUtils.cp(from, sysconf_dir)
end

## Environment

Ubuntu Bionic, Ruby 2.7.1

**Comment by bkuhlmann** [comment]
Hey @saigkill. :wave: It sounds like your your build is failing because you are using the latest version XDG, which is awesome, but your implementation hasn't been updated to use the new syntax. Can you confirm you are using XDG 3.0.0 or higher via your `Gemfile` and/or `Gemfile.lock`? You'll want to use the following syntax as `XDG.[]` syntax is no longer supported:

``` ruby
xdg = XDG::Environment.new
xdg.cache_home # <= Answers computed `$XDG_CACHE_HOME` value.
```

[Additional documentation can be found here](https://www.alchemists.io/projects/xdg/#_overview).

**Comment by saigkill** [comment]
Hey @bkuhlmann ,
sorry, you're right. I missed that information.
Thanks for clarification. :-)
