### ISSUE TITLE
Add XDG variable path expansion

### ISSUE THREAD

**Issue by noraj** [bkuhlmann/xdg#7]
A feature to expend path from a string. A bit like `File.expand_path('example.rb')` but also taking into account XDG dirs.

E.g. I'd like to expand `$XDG_DATA_HOME/mytool/myfolder` to `~/.local/share/mytool/myfolder` (relative) or `/home/example/.local/share/mytool/myfolder` (absolute).

## Why

I can't use a shell evaluation approach because a shell will evaluate shell variables like `$HOME` but not necessarily XDG ones. Example, if `$XDG_DATA_HOME` is not defined, it will return an empty string instead of the default XDG location. So I'll end up with a wrong path: `/mytool/myfolder`. It won't work with `File.expand_path` either as it's not XDG aware.

## How

Looking for `$XDG_*_HOME` or `$XDG_*_DIRS` in strings and replacing them with the appropriate value (from env vars or default value depending on the environment context).

**Comment by noraj** [comment]
For example, I'd like to be able to use `XDG.expend_path(path)` rather than creating a method similar to:

```ruby
        case path
        when /\$XDG_CONFIG_HOME/
          path.sub!('$XDG_CONFIG_HOME', xdg.config_home.to_s)
        when /\$XDG_DATA_HOME/
          path.sub!('$XDG_DATA_HOME', xdg.data_home.to_s)
        end
        return File.expand_path(path)
```

**Comment by bkuhlmann** [comment]
Hey Alexandre. :wave:

If I understand you correctly, this is already supported (with full path expansion). Consider the following:

``` ruby
# With XDG Data Home undefined.
ENV.delete "XDG_DATA_HOME"  # nil

xdg = XDG.new
xdg.data_home.join "mytool/myfolder"
# #<Pathname:/Users/demo/.local/share/mytool/myfolder>

# With XDG Data Home defined ($HOME override)
ENV["XDG_DATA_HOME"] = "/some/other/path"

xdg = XDG.new
xdg.data_home.join "mytool/myfolder"
# #<Pathname:/some/other/path/mytool/myfolder>

# With XDG Data Home defined (relative)
ENV["XDG_DATA_HOME"] = "some/other/path"

xdg = XDG.new
xdg.data_home.join "mytool/myfolder"
# #<Pathname:/Users/demo/some/other/path/mytool/myfolder>
```

There is no need to be looking for `$XDG_*_HOME` or `$XDG_*_DIRS` as all of this is dynamically handled for you since this is the sole purpose of this gem! You can control XDG behavior by setting those environment variables however you like and XDG (this gem) will behave accordingly.

Does this answer your question?

**Comment by noraj** [comment]
What you shows here wouldn't help me that much since the input I have is `$XDG_DATA_HOME/mytool/myfolder` and not `/mytool/myfolder` alone.

Changing the example to use `.join`, would do that but it's not easier. 

```ruby
        case path
        when /\$XDG_CONFIG_HOME/
          path = (xdg.config_home.join path.sub('$XDG_CONFIG_HOME', '')).to_s
        when /\$XDG_DATA_HOME/
          path = (xdg.data_home.join path.sub('$XDG_DATA_HOME', '')).to_s
        end
        return path
```

xdg.expand_path would check if env exists, evaluate `$XDG_*` and replace with env. var. or default value, then make the path absolute.

**Comment by bkuhlmann** [comment]
In that case, why not sub out what you need since this gem will always give you the fully resolved path. Example:

``` ruby
xdg = XDG.new

xdg.config_home.join("mytool/myfolder").sub(ENV["HOME"], "~")
#<Pathname:~/.config/mytool/myfolder>

xdg.data_home.join("mytool/myfolder").sub(ENV["HOME"], "~")
#<Pathname:~/.local/share/mytool/myfolder>
```

This means, no matter what *kind* of XDG path you create, you'd able replace the parts of the path you care about using the existing environment. In this case, I'm subbing `$HOME` but you could apply this pattern to any of the XDG environment variables as well.

What you are asking for is rather specialized and outside the scope of this gem (and the XDG Directory Specification in general). I'm hesitant to add a feature like this since it's a rather specialized use case.

Does the above help?

**Comment by noraj** [comment]
You could do that if you want to create something, and you have liberty to choose how to construct your path.

But what if I have an input with `$XDG_DATA_HOME/mytool/myfolder`? I mean with the actual `$XDG_DATA_HOME` in the string. I have to remove `$XDG_DATA_HOME` and have a switch case or if statement to call `xdg.data_home.join`, or `xdg.config_home` for `$XDG_CONFIG_HOME`.

I'm **not** in the case where I need to craft the path `$XDG_DATA_HOME` + `/mytool/myfolder` where I have the liberty to craft it the way I want. I'm in the case where I get a string like `$XDG_DATA_HOME/mytool/myfolder` from a config file and have to actually parse it and so evaluate it to replace `$XDG_DATA_HOME` by the actual XDG_DATA_HOME value.

So right now, as far as I understand, the gem only allows creating / forging path, where I need to evaluate / expand / parse path.

It's like for YAML, JSON or TOML libraries if they are able to dump Ruby object to markup or **load** markup into Ruby object or both.

**Comment by bkuhlmann** [comment]
Yeah, that make sense. You're dealing with string parsing rather than environment parsing. These are two different problems even though they are related. Definitely outside the scope of this gem (and the specification) because this gem is dealing with environment variables and related file paths but not string parsing/manipulation as you are describing.

The string parsing problem you are describing is unique enough that it'd be a different implementation that could use this gem as a dependency. Kind of like how the [Runcom](https://alchemists.io/projects/runcom) gem builds upon this XDG gem.

I'm going to close this since this problem is out-of-scope for this gem but we can continue the discussion if you like.

I do have a few questions in order to understand the larger picture of what your trying to tackle:

0. Why can't you use XDG, as it's designed to be used, to load your configuration data (i.e. YAML, TOML, INI, etc) and then go from there? Then you could used enhanced tooling like [Etcher](https://alchemists.io/projects/etcher) to supercharge your configurations/data even further?
1. Why do you have to load a configuration with XDG paths within iit the file, parse the strings as XDG paths, and then load? That seems like the inverse of what XDG is desiged for?
