### ISSUE TITLE
Hard requirement on Ruby version

### ISSUE THREAD

**Issue by noraj** [bkuhlmann/xdg#8]
Does xdg really only supports Ruby 3.3? https://github.com/bkuhlmann/xdg/commit/5f5397580bff6ca338a35249b11d92c475d31c28

Can't it work on Ruby 3.1 or 3.2?

On my tool I was planning to support [all Ruby maintained versions](https://www.ruby-lang.org/en/downloads/branches/) (3.1-3.3) but having xdg as a dependency I'm forced to sue only Ruby 3.3. It's really a shame as many distributions have only older version in the official repostories.

**Comment by bkuhlmann** [comment]
Hey Alexandre, yep, this is a hard requirement and [company policy](https://alchemists.io/rigor). Another reason is that I maintain ~45 projects all of which get little to no [sponsorship](https://github.com/sponsors/bkuhlmann) so if you take 45 times a Ruby version matrix of 3 (let's say, bare minimum) you end up with 135 builds, different releases, etc. That's simply not sustainable for no money. :cry:

You can, however, pull in the equivalent version of this gem for each of your own Ruby specific builds though. For instance, look through the [version release notes](https://alchemists.io/projects/xdg/versions) for details. You'll notice, each year, XDG gets a new major version bump in lock-step with each new Ruby version that drops of Christmas of each year. Knowing this, you can pin your build matrix to the specific version of this gem for your build matrix to achieve what you desire.

I'm going to close this issue since there is no further action but feel free to ask more questions if you like!

**Comment by noraj** [comment]
Hi Brooke, I understand, I guessed it was for easier maintainability.

I tried a conditional requirement depending on ruby version like that https://github.com/Acceis/aspisec/pull/4/commits/74d665eb5ec14ee264f7ab9aa503dc47241cc4fa but it fails on other CI like 3.2 (https://github.com/Acceis/aspisec/actions/runs/8604345437/job/23578231510?pr=4) because of the lock file. Removing the lock file won't be a good idea. I guess the correct way to do this would be to maintain a 3.1, 3.2 and 3.3 branch with each its own Gemfile and Gemfile.lock but that would make quite a lot of work.

I tried `bundle config set frozen false`, versioning .bundle (https://github.com/Acceis/aspisec/pull/4/commits/94c81c0652f8771ad70e7b4ca5c3c5ef153cd496) and removing rubocop warning about duplicate gem requirement (https://github.com/Acceis/aspisec/pull/4/commits/0de032b01ddb1428add53f2221a1d4932665fc22) and it seems to work (https://github.com/Acceis/aspisec/actions/runs/8604580167).

Else I saw there was a `BUNDLE_GEMFILE` for the CI ([ruby/setup-ruby)](https://github.com/ruby/setup-ruby)) that would allow specifying a Gemfile to bundler, so I could have Gemfile, Gemfile3.2 and Gemfile3.1 with a more complex CI workflow file.

I don't know if you had something smarter in mind, else my option are:

- keep the unfrozen Gemfile
- remove xdg dependency and do something manually
- test only 3.3 on the CI but keep 3.1-3.3 in the Gemspec (because anyway for this specific project I only run rubocop and on the .rucocop.yml I have `TargetRubyVersion: 3.1`, so my CI matrix with virtually always gives the same results unless there is an incompatibility between rubocop and the ruby version, have a ruby version matrix is much more useful for projects with unit tests)
- totally drop 3.1-3.2 and keep only 3.3 in the Gemspec

**Comment by bkuhlmann** [comment]
Sorry for the slow response. I'm traveling this week, so my access and time is limited more than usual. I'll have more availability at the end of this week to look at this more closely because I need some time to test out more of the scenarios you posted above.

My initial thought was, yes, swap out different `Gemfile` and `Gemfile.lock` versions (I seem to recall this being the recommendation in Travis CI builds in years past). Another option might be using Bundler's `install_if` directive ([documentation](https://bundler.io/v2.5/man/gemfile.5.html#INSTALL_IF)). Not sure if that would be of interest but might help.

Let me think on this more and I'll get back to you.

**Comment by noraj** [comment]
Thank you for your contribution to the Ruby ecosystem. Also thank you for taking some time to answer me and trying to help. I totally understand your position about limiting the maintenance effort you put your projects when you have a large number to maintain for open-source on your free time you get nearly no benefit from. In fact, I'm in a similar position, dedicating a lot of my free time to open-source projects (either mine or others) and have very large number of projects to maintain. However, my projects are far less important and less used, so I can allow myself a less strict policy, so I usually support the maximum number of ruby versions and only drop them when a dependency or the CI drop support for it. For them gems, I use dependabot or depfu to maintain the latest version for each dependency. As Rubygems, gemspec and Gemfile are built there is no room for conditional dependency based on Ruby version. So all I can do is a patch-up job either with several branches, several Gemfiles or using duplicate gem dependency requirement and unfrozen Gemfile (https://github.com/Acceis/aspisec/pull/4/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55f) which is not satisfactory and will be hard to maintain. So my conclusion was that the xdg requirement on Ruby version is too hard for my project. With only Ruby 3.3 it can't run on any major distribution (https://repology.org/project/ruby/versions) not even ArchLinux, so it would require the users of my project to install a virtual ruby environment like with rbenv of asdf-vm. I don't want that. As I have a very light use of XDG Base Directory spec, I don't really need the xdg gem. So I chose to switch to something much simpler (https://github.com/Acceis/aspisec/pull/5/files#diff-782ce8c4bc9ba5ca25775a2b7ac890de1bc933eaf555c6a1b2cac77184a038b2): sxdg that has no ruby requirement as is just a file with a bunch of constants (https://my.diffend.io/gems/sxdg/1.0.0#d2h-562169). That way it's extremely easy to maintain and has no constraint on my project as it has no requirement and will probably never be updated. So I'm sorry, I'm not trying to be rude and I have a great share of respect for what you are doing, but I think the better option for my project was to not use xdg. Again in thank you for the advices, I learned a bunch of stuff trying to twist the Gemfile to solve this challenge.

**Comment by bkuhlmann** [comment]
OK, I'm back from traveling and had time to look at this more closely. I see where you are coming from and choosing SXDG is an interesting choice -- in terms of delayed technical debt -- in that you are giving up future development and support in favor a gem that isn't maintained (including no Ruby version requirements).

...but, yeah, if you move away from using XDG entirely, then you no longer have a dependency at all which definitely simplifies project maintain on your side. Always best if you can swing it (as the saying goes: no code is the best code).

Otherwise, yeah, I can't help you in terms of needing to support multiple older versions of Ruby unless you properly tag your own project and pin each of your versions to a specific version of Ruby as well.
